### ISSUE TITLE
Implement build pipeline

### ISSUE THREAD

**Issue by jofme** [jofme/D365FinanceToolbox#2]
Implement build pipeline

**Comment by FH-Inway** [comment]
Thanks for your work on https://github.com/ameyer505/D365FOAdminToolkit/pull/28
I did a bit of snooping on your profile and discovered this lovely repo. Happy to help with this issue, already created pr #23 for it. It's basically the same build action that the [D365FOAdminToolkit](https://github.com/ameyer505/D365FOAdminToolkit) has. It is based on the nice work of [FSC-PS for GitHub](https://github.com/fscpscollaborative/fscps) and the [simple template](https://github.com/FH-Inway/fscps.fscsimpletpl) I created for it.

**Comment by jofme** [comment]
Thanks @FH-Inway!
